name: build docker image
# Controls when the action will run.
on:
  push:
    tags:
      - 'v*.*.*' ## on tag v*.*.*, build and push to dockerhub

jobs:
  buildx:
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, 'v') && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate BuildArg ver
        id: generate_build_arg_ver
        run: echo "::set-output name=ver::$(git log -1 --pretty=format:"%h-%as")"

      - name: Extract Tag
        id: extract_tag
        run: echo "::set-output name=tag::$(echo $GITHUB_REF | cut -d '/' -f 3)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            ver=${{ steps.generate_build_arg_ver.outputs.ver }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tonutils-storage:${{ steps.extract_tag.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/tonutils-storage:latest
